account/urls.py
#! /usr/bin/env python3
# coding: UTF-8

""" Account URLS """


# imports
from django.conf.urls import url
from . import views


app_name = 'account'

urlpatterns = [
    url(r'^access_account/$', views.access_account, name="access_account"),
    url(r'^create_account/$', views.create_account, name="create_account"),
    url(r'^my_account/$', views.my_account, name="my_account")
]

food/urls.py
#! /usr/bin/env python3
# coding: UTF-8

""" Food URLS """


# imports
from django.conf.urls import url
from . import views


app_name = 'food'

urlpatterns = [
    url(r'^result/$', views.result, name="result"),
    url(r'^detail/$', views.detail, name="detail"),
    url(r'^favorites/$', views.favorites, name="favorites")
]

purbeurre/urls.py
#! /usr/bin/env python3
# coding: UTF-8

"""purbeurre URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


# imports
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls import url
from food import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mentions_legal/$', views.mentions_legal, name='mentions_legal'),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^food/', include('food.urls', namespace='food')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

food/models.py
#! /usr/bin/env python3
# coding: UTF-8

""" Models """


# Imports
from django.db import models
from django.contrib.auth import get_user_model


class Categorie(models.Model):
    """ Categorie model
    field : name """
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Food(models.Model):
    """ Food model
    fields : name, categorie, nutrition_grade, url_picture,
    link, energy, proteins, fat, carbohydrates, sugars,
    fiber, sodium, favorites """
    User = get_user_model()
    name = models.CharField(max_length=120, unique=True)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    nutrition_grade = models.CharField(max_length=1)
    url_picture = models.URLField(unique=True)
    link = models.URLField(unique=True)
    energy = models.CharField(max_length=10, null=True)
    proteins = models.CharField(max_length=10, null=True)
    fat = models.CharField(max_length=10, null=True)
    carbohydrates = models.CharField(max_length=10, null=True)
    sugars = models.CharField(max_length=10, null=True)
    fiber = models.CharField(max_length=10, null=True)
    sodium = models.CharField(max_length=10, null=True)
    favorites = models.ManyToManyField(User)

    def __str__(self):
        return self.name, self.categorie, self.nutrition_grade, self.url_picture, self.link, \
               self.energy, self.proteins, self.fat, self.carbohydrates, self.sugars, self.fiber, \
               self.sodium

food/views.py
#! /usr/bin/env python3
# coding: UTF-8

""" Food views :
index, result, detail, favorites, mentions_legal """


# imports
from django.shortcuts import render
from django.contrib.auth import logout, get_user_model
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from requests.exceptions import ConnectionError
from food.classes import database
from food.models import Food
from account.forms import Account


def index(request):
    """ index view :
    insert data in the database if database is empty,
    logout the user and display the index page (home) """

    # USER'S DISCONNECTION AND DISPLAY THE INDEX PAGE
    # if the user clicks on the logout logo
    if request.method == 'POST':
        disconnection = request.POST.get('disconnection', 'False')
        if request.user.is_authenticated and disconnection == 'True':
            logout(request)
            context = {'message': "Vous êtes déconnecté."}
            return render(request, 'food/index.html', context)

    # INSERT DATA IF THE DATABASE IS EMPTY
    # DISPLAY THE INDEX PAGE
    try:
        bdd = database.Database()
        bdd.insert_data()
        return render(request, 'food/index.html')
    except ConnectionError:
        context = {'message': "Problème de connexion"}
        return render(request, 'food/index.html', context)


def result(request):
    """ result view :
    display the food data in the result page,
    if there is no result
    display an error message in the index page,
    add id of the favorites food in the context because
    if the user has already registered the food,
    we will not display the floppy logo,
    save the food selected by the user """

    if request.method == 'POST':
        # SAVE FOOD SELECTED BY THE USER
        # if user is authenticated
        save_id_food = request.POST.get('id', None)
        if save_id_food and request.user.is_authenticated:
            id_user = request.user.id
            food = Food.objects.get(id=save_id_food)
            user = get_user_model()
            user = user.objects.get(id=id_user)
            food.favorites.add(user)

        if save_id_food is None:
            # get the name food searched
            food = request.POST.get('search')
            request.session['food'] = food

            # DISPLAY THE INDEX PAGE WITH AN ERROR MESSAGE
            # if there is no food searched
            if not food:
                context = {'message': "Vous n'avez rien demandé"}
                return render(request, 'food/index.html', context)

            context = {'search': food}

            # get the categorie of the food searched
            re_food = '^.*'+food+'.*$'
            re_food = re_food.replace(' ', '.*')
            re_food = r'{}'.format(re_food)
            name = Food.objects.filter(name__iregex=re_food)[:1]
            categorie_food = name.values_list('categorie')

            # DISPLAY THE RESULT PAGE
            # DISPLAY THE RESULT ON PAGE 1
            # if there is food searched
            # and if the categorie exists
            if categorie_food:

                # get data of all foods of the same categorie
                # ordered by nutrition grade
                categorie_food = categorie_food[0]
                data = Food.objects.filter(categorie=categorie_food)
                foods_data = data.order_by('nutrition_grade')

                # use paginator :
                # display of page 1 of result
                paginator = Paginator(foods_data, 18, orphans=4)
                page = request.GET.get('page')
                try:
                    foods_data = paginator.get_page(page)
                except PageNotAnInteger:
                    foods_data = paginator.page(1)
                except EmptyPage:
                    foods_data = paginator.page(paginator.num_pages)
                context['foods_data'] = foods_data

                # DOES NOT DISPLAY THE FLOPPY LOGO
                # if the user has already registered the food
                if request.user.is_authenticated:
                    # get the favorites foods id
                    user = get_user_model()
                    favorites_id = []
                    id_user = request.user.id
                    for elt in user(id=id_user).food_set.values_list('id'):
                        favorites_id.append(elt[0])
                    context['favorites_id'] = favorites_id
                else:
                    context['favorites_id'] = []

                return render(request, 'food/result.html', context)

            # DISPLAY THE INDEX PAGE WITH AN ERROR MESSAGE
            # if there is food searched
            # but that the categorie don't exists
            else:
                context = {"message": "Pas de résultat pour l'aliment {}.".format(food)}
                return render(request, 'food/index.html', context)

    # DISPLAY THE RESULT PAGE
    # DISPLAY THE RESULT ON SEVERAL PAGES : page > 1
    if 'food' in request.session:
        food = request.session['food']
        context = {'search': food}

        # get data of all foods of the same categorie
        list_food = food.split()
        for word in list_food:
            name = Food.objects.filter(name__icontains=word)[:1]
            categorie_food = name.values_list('categorie')
            categorie_food = categorie_food[0]
            data = Food.objects.filter(categorie=categorie_food)
            foods_data = data.order_by('nutrition_grade')

            # use paginator :
            # display of pages > 1 of result
            paginator = Paginator(foods_data, 18, orphans=4)
            page = request.GET.get('page')
            try:
                foods_data = paginator.get_page(page)
            except PageNotAnInteger:
                foods_data = paginator.page(1)
            except EmptyPage:
                foods_data = paginator.page(paginator.num_pages)
            context['foods_data'] = foods_data

            # DOES NOT DISPLAY THE FLOPPY LOGO
            # if the user has already registered the food
            if request.user.is_authenticated:
                # get the favorites foods id
                user = get_user_model()
                favorites_id = []
                id_user = request.user.id
                for elt in user(id=id_user).food_set.values_list('id'):
                    favorites_id.append(elt[0])
                context['favorites_id'] = favorites_id
            else:
                context['favorites_id'] = []

        return render(request, 'food/result.html', context)


def detail(request):
    """ detail view :
    get the data of the food selected by the user
    and display the detail page """

    # DISPLAY THE DETAIL PAGE
    # get id of the food selected
    id_food = request.POST.get('id_food', None)

    # get the data of the food selected
    food = Food.objects.values_list('name', 'nutrition_grade', 'url_picture',
                                    'link', 'energy', 'proteins', 'fat',
                                    'carbohydrates', 'sugars', 'fiber', 'sodium')
    food_data = food.get(id=id_food)
    context = {}
    name_data = ('name', 'nutrition_grade', 'url_picture', 'link', 'energy', 'proteins', 'fat',
                 'carbohydrates', 'sugars', 'fiber', 'sodium')
    for i, elt in enumerate(name_data):
        context[elt] = food_data[i]

    return render(request, 'food/detail.html', context)


def favorites(request):
    """ favorites view :
        get the favorites food data of the user
        and display the favorites page,
        delete the favorite food selected by the user """

    # DELETE THE FOOD SELECTED BY THE USER
    if request.method == 'POST' and request.user.is_authenticated:
        id_food = request.POST.get('id', None)
        id_user = request.user.id
        food = Food.objects.get(id=id_food)
        user = get_user_model()
        user = user.objects.get(id=id_user)
        food.favorites.remove(user)

    # RETURN TO THE ACCESS_ACCOUNT PAGE
    # if user is not authenticated
    if not request.user.is_authenticated:
        form = Account()
        message = ["Veuillez vous connecter pour accéder à vos favoris."]
        context = {'form': form, 'message': message, 'color': 'red'}
        return render(request, 'account/access_account.html', context)

    # DISPLAY THE FAVORITES PAGE
    # if user is authenticated
    # get the favorites food data
    user = get_user_model()
    id_user = request.user.id
    data = user(id=id_user).food_set.all()
    context = {'data': data}

    return render(request, 'food/favorites.html', context)


def mentions_legal(request):
    """ mentions_legal view :
    display the mentions_legal page """
    return render(request, 'food/mentions_legal.html')

food/templates/food/base.html
<!DOCTYPE html>
<html lang="fr">
{% load static %}


<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>OC Projet 8</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'food/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'food/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'food/css/creative.min.css' %}" rel="stylesheet">

  <!-- Import css file -->
  <link rel="stylesheet" href="{% static 'food/css/creative.css' %}">

  <!-- Fonts -->
  <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">

  {% block link %}
  {% endblock %}

  <!-- Favicon logo -->
  <link rel="icon" type="icon/png" href="{% static 'food/img/favicon.png' %}"/>

</head>


<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <img src="{% static 'food/img/logo_purbeurre.png' %}" alt="logo Purbeurre">
      <h1 class="navbar-brand js-scroll-trigger">&nbsp;&nbsp;PurBeurre</h1>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0 logoUl">
          <li class="nav-item search">
            <form action="{% url 'food:result' %}" method="post">{% csrf_token %}
              <input type="text" id="searchTextarea" placeholder="  Chercher" name="search">
            </form>
          </li>

          {% if authenticated == 'False' %}
          <li class="nav-item logo" id="userLogoLi">
            <a onmouseover="document.photo.src='{% static 'food/img/logo_user_black.png' %}'"
            onmouseout="document.photo.src='{% static 'food/img/logo_user.png' %}'"
            href="{% url 'account:access_account' %}" ><img class="center" src="{% static 'food/img/logo_user.png' %}" name="photo" alt="logo user"></a>
            <p>M'identifier</p>
          </li>
          {% else %}
          <li class="nav-item logo" id="userLogoLi">
            <a onmouseover="document.photo.src='{% static 'food/img/logo_user_green2.png' %}'"
            onmouseout="document.photo.src='{% static 'food/img/logo_user_green.png' %}'"
            href="{% url 'account:my_account' %}" ><img class="center" src="{% static 'food/img/logo_user_green.png' %}" name="photo" alt="logo user"></a>
            <p>Mon compte</p>
          </li>
          {% endif %}

          <li class="nav-item logo" id="carrotLogoLi">
            <a href="{% url 'food:favorites' %}" ><img class="center" id="carrotLogo" src="{% static 'food/img/logo_carrot.png' %}" alt="logo carrot"></a>
            <p>Mes favoris</p>
          </li>

          <li class="nav-item logo">
            <form action="{% url 'index' %}" method="post">{% csrf_token %}
              <input type="hidden" name="disconnection" value="True" />
              <input class="center" type="image" src="{% static 'food/img/logo_exit.png' %}" alt="logo exit" />
            </form>
            {% if authenticated == 'False' %}
            <p>Accueil</p>
            {% else %}
            <p>Déconnexion</p>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <!-- Masthead -->
  <header class="masthead">

    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          {% block content2 %}
          {% endblock %}
        </div>
      </div>
    </div>

  </header>

{% block content %}
{% endblock %}


<!-- Footer -->
  <footer class="bg-light py-5">

    <div class="container">
      <div class="row justify-content-around">
        <a href="{% url 'mentions_legal' %}" class="small text-white m-auto">Mentions légales</a>
        <a href="{% url 'index' %}#ancre" class="small text-white m-auto">Contact</a>
      </div>
    </div>

  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'food/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'food/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'food/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'food/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'food/js/creative.js' %}"></script>

</body>

</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% load static %}


{% block link %}
<!-- Import css file -->
<link rel="stylesheet" href="{% static 'food/css/style.css' %}">
{% endblock %}


{% block content2 %}
<h2 class="text-white">{{ name }}</h2>
{% endblock %}


{% block content %}
<!-- About Section -->
<section class="page-section bg-primary" id="about">
  <div class="container">
    <div class="row justify-content-around detail" id="{{ url_picture }}">
      <div class="col-lg-6 text-center">
        <h4>Nutriscore</h4><br>
        {% if nutrition_grade == "a" %}
        <a><span class="medium">A </span>B C D E</a>
        {% elif nutrition_grade == "b" %}
        <a>A <span class="medium">B </span>C D E</a>
        {% elif nutrition_grade == "c" %}
        <a>A B <span class="medium">C </span>D E</a>
        {% elif nutrition_grade == "d" %}
        <a>A B C <span class="medium">D </span>E</a>
        {% elif nutrition_grade == "e" %}
        <a>A B C D<span class="medium">E </span></a>
        {% endif %}
        <br><br><br><br><a href='{{ link }}' target="_blank"><button>Voir la fiche d'OpenFoodFacts</button></a>
      </div>
      <div class="col-lg-6 text-left">
        <h4> Repères nutritionnels pour 100g :</h4>
        <ul>
          <li>Energie : {{ energy }} KJ</li>
          <li>Protéines : {{ proteins }} g</li>
          <li>Lipides : {{ fat }} g</li>
          <li>Glucides : {{ carbohydrates }} g<br>dont sucres : {{ sugars }} g</li>
          <li>Fibres : {{ fiber }} g</li>
          <li>Sel : {{ sodium }} g</li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock %}

food/templates/food/favorites.html
{% extends 'food/base.html' %}
{% load static %}


{% block link %}
<!-- Import css file -->
<link rel="stylesheet" href="{% static 'food/css/style.css' %}">
{% endblock %}


{% block content2 %}
<h2 class="text-white">Mes aliments</h2>
{% endblock %}


{% block content %}
<!-- About Section -->
<section class="page-section bg-primary" id="about">
  <div class="container">
     <div class="row justify-content-around">
        {% for food in data %}
        <div id="delete{{ food.id }}">
           <a href="{{ food.link }} ">
              <img id="image"  src="{{ food.url_picture }}" alt="food image" height="196" width="196">
           </a><br>
           <div class="max-width"><p id="nameFood" class="text-center"> {{ food.name }}</p>
           </div>
           <div class="delete" id="{{ food.id }}">
              <p class="text-center">
                 <i id="delete" class="far fa-trash-alt"></i> Supprimer
              </p>
           </div>
        </div>
        {% endfor %}
     </div>
  </div>
</section>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}


{% block content2 %}
  <p class="text-white-75 font-weight-light mb-5">{{ message }}</p>
  <h1 class="text-white">Du gras, oui, mais de qualité ! </h1>
  <hr class="divider my-4">
</div>
  <div class="col-lg-8 align-self-baseline">
    <h2 class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
    <form action="{% url 'food:result' %}" method="post">{% csrf_token %}
      <input type="text" class="js-scroll-trigger" id="productTextarea" placeholder="  Produit" name="search">
      <input type="submit" onclick="location.href='{% url 'food:result' %}'" value="Chercher"/><br><br>
    </form>
  </div>
{% endblock %}


{% block content %}
<!-- About Section -->
<section class="page-section bg-primary" id="about">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="text-black mt-0">Colette et Remy</h2>
        <hr class="divider light my-4">
        <p class="text-black mb-4">Pur Beurre est l'initiative de deux amoureux de la gastronomie française,
          Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.
        </p>
        <div class="row justify-content-between">
          <img class="col-lg-4 btn btn-light btn-xl js-scroll-trigger" src="{% static 'food/img/colette.png' %}" alt="image Colette">
          <img class="col-lg-6 btn btn-light btn-xl js-scroll-trigger" src="{% static 'food/img/remy.png' %}" alt="image Remy">
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Contact Section -->
<section class="page-section" id="contact">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <h2 class="mt-0">Contactez-nous !</h2>
        <hr class="divider my-4">
        <p class="text-muted mb-5">Besoin d'informations ?<br>Nous sommes joignables du lundi au samedi de 8h à 19h.</p>
      </div>
    </div>
    <div class="row" id="ancre">
      <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
        <div>+0 (000) 000-0000</div>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
        <!-- Make sure to change the email address in anchor text AND the link below! -->
        <a class="d-block" href="mailto:contact@yourwebsite.com">purbeurre@purbeurre.com</a>
      </div>
    </div>
  </div>
</section>
{% endblock %}

food/templates/food/result.html
{% extends 'food/base.html' %}
{% load static %}


{% block link %}
<!-- Import css file -->
<link rel="stylesheet" href="{% static 'food/css/style.css' %}">
{% endblock %}


{% block content2 %}
<h2 class="text-white">Aliment recherché : {{ search }}</h2>
{% endblock %}


{% block content %}
<!-- About Section -->
<section class="page-section bg-primary" id="about">
   <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h3 class="text-black mt-0">Vous pouvez remplacer cet aliment par :</h3>
        </div>
      </div>
      <div class="row">
        {% for food_data in foods_data %}
          {% if food_data.name %}
          <div class="result" id="{{ food_data.url_picture }}">
              <form action="{% url 'food:detail' %}" method="post">{% csrf_token %}
                <p>
                  <input type="hidden" name="id_food" value="{{ food_data.id }}" />
                  <input id="image" type="image" height="196" width="196" src="{{ food_data.url_picture }}" />
                </p>
              </form>
              <div class="foreground">
                <p id="nutriscore">{{ food_data.nutrition_grade }}</p>
              </div>
              <br><div class="max-width"><p id="nameFood" class="text-center">{{ food_data.name }}</p></div>
              <div class="save" id="{{ food_data.id }}">
                {% if food_data.id in favorites_id and authenticated == 'True' %}
                {% elif authenticated == 'True' %}
                <p class="text-center" >
                    <i id="floppy" class="fas fa-save"></i> Sauvegarder
                </p>
                {% elif authenticated == 'False' %}
                <a href="{% url 'account:access_account' %}"><p class="text-center" >
                    <i id="floppy" class="fas fa-save"></i> Sauvegarder
                </p></a>
                {% endif %}
             </div>
          </div>
          {% endif %}
        {% endfor %}
      </div>

      <div class="pagination">
        <span class="step-links" id="direction-pages"><br><br><br>
            {% if foods_data.has_previous %}
            <a href="?page=1">Retour page 1</a><br>
            <a href="?page={{ foods_data.previous_page_number }}">&laquo; précédent&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a>
            {% endif %}
            {% if foods_data.has_next %}
            <a href="?page={{ foods_data.next_page_number }}">suivant &raquo;</a>
            {% endif %}
            <br><br><span class="current" id="pages">Page {{ foods_data.number }} sur {{ foods_data.paginator.num_pages }}
            </span>
        </span>
      </div>
   </div>
</section>
{% endblock %}